[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Copyright © OpenCHAMI a Series of LF Projects, LLC. For web site terms of use, trademark policy and other project policies please see <a href=https://lfprojects.org>lfprojects.org</a>.'
  